from .AddressPage import AddressPage
from .CheckoutPage import CheckoutPage
from .HomePage import HomePage
from .LoginPage import LoginPage
from .OrderConfirmation import OrderConfirmationPage
from .PaymentPage import OrderSummaryPage
from .ShippingPage import ShippingAddressPage
from .ShoppingCart import ShoppingCartSummaryPage
from .SummaryPage import OrderSummaryPage
from .SummerDressesCatalogPage import SummerDressesCatalogPage
